#!/bin/bash

# Install the JupyterLab dask-labextension
jupyter labextension install dask-labextension @jupyter-widgets/jupyterlab-manager

# Install the JupyterLab execute-time extension
#jupyter labextension install jupyterlab-execute-time @jupyter-widgets/jupyterlab-manager
